### ISSUE TITLE
Call revert error on simple example on zkSync

### ISSUE THREAD

**Issue by rareadam** [element-market/element-js-sdk#8]
I tried the new support for zkSync but wasn't able to run the most basic example. I know for sure my keys are setup correctly but I get a revert-error when trying to list something. Here is my example code:

```js
import { ElementSDK, Network } from 'element-js-sdk'
import { ethers } from 'ethers'
import { JsonRpcProvider } from '@ethersproject/providers'

// zksync mainnet
const rpcUrl = 'https://zksync-era.rpc.thirdweb.com'
const privateKey = '*******'
const apiKey = '*******'

const jsonRpcProvider = new JsonRpcProvider(rpcUrl);
const signer = new ethers.Wallet(privateKey, jsonRpcProvider);

const sdk = new ElementSDK({
    networkName: Network.ZkSync,
    isTestnet: false,
    apiKey: apiKey,
    signer: signer
});

const r = await sdk.makeERC721SellOrders({
    items: [
        {
            erc721TokenAddress: '0x2f31ac0c3c4bc1ed24bdebfef33c3f2a756fa9b0',
            erc721TokenId: 1,
            paymentTokenAmount: 1e17
        }
    ]
})

```

This here is the error:

```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getSDKApprovalsAndCounter(address,(uint8,address,address)[])", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (/home/trusch/Code/zksync/listing-script/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/trusch/Code/zksync/listing-script/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Interface.decodeFunctionResult (/home/trusch/Code/zksync/listing-script/node_modules/@ethersproject/abi/lib/interface.js:388:23)
    at Contract.<anonymous> (/home/trusch/Code/zksync/listing-script/node_modules/@ethersproject/contracts/lib/index.js:395:56)
    at step (/home/trusch/Code/zksync/listing-script/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/trusch/Code/zksync/listing-script/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/trusch/Code/zksync/listing-script/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getSDKApprovalsAndCounter(address,(uint8,address,address)[])',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x4ff83aa3a2a993270c7921ce6f22892213c3c446',
  args: [
    '0x0f084201387e594bc7f862ba6e52f6598d13fb06',
    [
      {
        tokenType: 0,
        tokenAddress: '0x2f31ac0c3c4bc1ed24bdebfef33c3f2a756fa9b0',
        operator: '0x64848eefbc2921102a153b08fa64536ae1f8e937'
      }
    ]
  ],
  transaction: {
    data: '0xa40224c90000000000000000000000000f084201387e594bc7f862ba6e52f6598d13fb060000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f31ac0c3c4bc1ed24bdebfef33c3f2a756fa9b000000000000000000000000064848eefbc2921102a153b08fa64536ae1f8e937',
    to: '0x4ff83aA3a2a993270C7921ce6F22892213C3C446',
    from: '0x0f084201387E594Bc7f862Ba6e52f6598D13fB06'
  }
}
```

I'm using the latest version of the SDK and the same version of ethers as in the latest package.json from this repo.

Any hint would be apprectiated!

**Comment by rareadam** [comment]
@kyoukisu If you have any input, please let us know!

**Comment by kyoukisu** [comment]
I'd better not to explain how i managed to make it working... It's very horrible by me

**Comment by element-market** [comment]
fixed
